apiVersion: v1
kind: Template
labels:
  app: authproxy
  template: authproxy-imagestream
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: AuthProxy - ImageStream
      see https://github.com/Worteks/docker-authproxy
    iconClass: icon-openshift
    openshift.io/display-name: AuthProxy
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: authproxy
  name: authproxy-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet AuthProxy image
    name: authproxy-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
